name: Lighthouse CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli

      - name: Run Lighthouse CI (prod URL or env)
        env:
          LHCI_BASE_URL: ${{ secrets.LHCI_BASE_URL }}
        run: |
          lhci autorun --config=./lighthouserc.json || (
            echo "Lighthouse CI failed" && exit 1
          )

